[package]
name = "cpp_common"
version = "0.1.0"
authors = ["Michael Layzell <michael@thelayzells.com>"]

[dependencies]
syn = { path = "../../syn", version = "0.11", features = ["full", "visit"] }
synom = { path = "../../syn/synom", version = "0.11" }
quote = "0.3"
