[package]
name = "cpp_macros"
version = "0.2.0"
authors = ["Michael Layzell <michael@thelayzells.com>"]

[lib]
proc-macro = true

[dependencies]
lazy_static = "0.2.2"
cpp_common = { path = "../cpp_common", version = "0.2.0" }
cpp_synom = { path = "../cpp_syn/synom", version = "0.12" }
cpp_syn = { path = "../cpp_syn", version = "0.12", features=["full", "visit"] }
quote = "0.3"
