[package]
name = "cpp_macros"
version = "0.1.0"
authors = ["Michael Layzell <michael@thelayzells.com>"]

[lib]
proc-macro = true

[dependencies]
lazy_static = "0.2.2"
cpp_common = { path = "../cpp_common", version = "0.1" }
synom = { path = "../../syn/synom", version = "0.11" }
syn = { path = "../../syn", version = "0.11", features=["full", "visit"] }
quote = "0.3"
